# Generated by Django 2.2.4 on 2021-04-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDojoReads', '0002_auto_20210429_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='comentadoPor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarista', to='appDojoReads.Usuario'),
        ),
    ]
